#!/usr/bin/env bash
# =============================================================================
# setup-vps.sh — NightHunt VPS Bootstrap (chạy 1 lần trên VPS mới)
#
# Cách dùng (SSH vào VPS rồi chạy):
#   curl -fsSL https://raw.githubusercontent.com/nvanquyet/nighthunt_server/main/infra/scripts/setup-vps.sh | bash
# Hoặc copy lên VPS rồi:
#   chmod +x setup-vps.sh && sudo ./setup-vps.sh
# =============================================================================
set -euo pipefail

DEPLOY_DIR="/opt/nighthunt"
GITHUB_OWNER="nvanquyet"
REPO="nighthunt_server"
RAW_URL="https://raw.githubusercontent.com/${GITHUB_OWNER}/${REPO}/main"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   NightHunt VPS Bootstrap                   ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ── 1. Cài Docker ────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "==> Cài Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  echo "    [OK] Docker installed"
else
  echo "==> Docker đã có: $(docker --version)"
fi

# ── 2. Cài Docker Compose plugin ─────────────────────────────────────────────
# docker compose v2 plugin can be installed in user-local path (~/.docker/cli-plugins)
# or system-wide (/usr/local/lib/docker/cli-plugins or /usr/libexec/docker/cli-plugins).
# When running as root via sudo, the user-local path is not on PATH, so we check all
# known locations explicitly.
_compose_ok() {
  docker compose version &>/dev/null && return 0
  for _p in /usr/local/lib/docker/cli-plugins/docker-compose \
             /usr/libexec/docker/cli-plugins/docker-compose \
             /usr/lib/docker/cli-plugins/docker-compose; do
    [ -x "$_p" ] && return 0
  done
  return 1
}
if ! _compose_ok; then
  echo "==> Cài Docker Compose plugin..."
  # Install compose v2 plugin to the system-wide CLI plugins directory
  COMPOSE_DIR="/usr/local/lib/docker/cli-plugins"
  mkdir -p "$COMPOSE_DIR"
  COMPOSE_VERSION=$(curl -fsSL https://api.github.com/repos/docker/compose/releases/latest \
    | grep '"tag_name"' | head -1 | cut -d'"' -f4)
  COMPOSE_VERSION="${COMPOSE_VERSION:-v2.35.0}"
  curl -fsSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
    -o "${COMPOSE_DIR}/docker-compose"
  chmod +x "${COMPOSE_DIR}/docker-compose"
  echo "    [OK] Docker Compose ${COMPOSE_VERSION} installed (system-wide)"
else
  echo "==> Docker Compose đã có: $(docker compose version 2>/dev/null || echo 'v2 plugin')"
fi

# ── 3. Tạo thư mục deploy ────────────────────────────────────────────────────
echo "==> Tạo thư mục $DEPLOY_DIR..."
mkdir -p "$DEPLOY_DIR/certs"
echo "    [OK] $DEPLOY_DIR"

# ── 4. Copy docker-compose.yml từ repo ──────────────────────────────────────
echo "==> Copy docker-compose.yml..."
# Detect if running from inside the cloned repo (local / VPS with git clone).
# Falls back to authenticated GitHub download when piped via curl | bash.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)" || SCRIPT_DIR=""
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." 2>/dev/null && pwd)" || REPO_ROOT=""
if [ -f "${REPO_ROOT}/docker-compose.yml" ]; then
  cp "${REPO_ROOT}/docker-compose.yml" "${DEPLOY_DIR}/docker-compose.yml"
  echo "    [OK] docker-compose.yml (local copy)"
elif [ -n "${GITHUB_TOKEN:-}" ]; then
  curl -fsSL -H "Authorization: token ${GITHUB_TOKEN}" \
    "${RAW_URL}/docker-compose.yml" -o "${DEPLOY_DIR}/docker-compose.yml"
  echo "    [OK] docker-compose.yml (downloaded)"
else
  echo "    [WARN] Cannot find docker-compose.yml locally and GITHUB_TOKEN not set."
  echo "           Copy it manually: scp docker-compose.yml ${DEPLOY_DIR}/"
  echo "           Or re-run with: GITHUB_TOKEN=<pat> bash setup-vps.sh"
fi

# ── 5. Tạo .env.production nếu chưa có ──────────────────────────────────────
ENV_FILE="${DEPLOY_DIR}/.env.production"
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Tạo .env.production template..."
  VPS_IP=$(curl -s ifconfig.me 2>/dev/null || echo "YOUR_VPS_IP")
  cat > "$ENV_FILE" <<EOF
# NightHunt Production Environment
# Generated by setup-vps.sh — $(date +%Y-%m-%d)
# docker-compose --env-file .env.production up -d

ENV_FILE=.env.production

# ── Database ──────────────────────────────────────────────────
MYSQL_DATABASE=nighthunt
MYSQL_USER=nighthunt
MYSQL_PASSWORD=CHANGE_ME_STRONG_PASSWORD
MYSQL_ROOT_PASSWORD=CHANGE_ME_ROOT_PASSWORD
DB_URL=jdbc:mysql://mysql:3306/nighthunt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
DB_USERNAME=nighthunt
DB_PASSWORD=CHANGE_ME_STRONG_PASSWORD

# ── Redis ─────────────────────────────────────────────────────
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=CHANGE_ME_REDIS_PASSWORD

# ── Backend (HTTP — nginx terminates TLS on port 443) ─────────
SERVER_PORT=8080
SSL_ENABLED=false
SSL_KEYSTORE=
SSL_KEYSTORE_PASSWORD=
SSL_KEYSTORE_TYPE=
SSL_KEY_ALIAS=
USE_HTTPS=true
API_BASE_URL=https://${VPS_IP}
CORS_ALLOWED_ORIGINS=https://${VPS_IP}

# ── JWT & Security ────────────────────────────────────────────
# Generate: openssl rand -hex 32
JWT_SECRET=CHANGE_ME_MIN_64_HEX_CHARS
JWT_EXPIRATION=900000
REFRESH_TOKEN_EXPIRY_DAYS=30
CSRF_ENABLED=false

# ── Spring ────────────────────────────────────────────────────
SPRING_PROFILES_ACTIVE=prod

# ── Let's Encrypt ─────────────────────────────────────────────
LE_EMAIL=admin@${VPS_IP}

# ── Dedicated Server ──────────────────────────────────────────
VPS_PUBLIC_IP=${VPS_IP}
DS_DOCKER_ENABLED=true
DS_IMAGE_REF=ghcr.io/nvanquyet/nighthunt-ds:latest
ADMIN_SECRET=CHANGE_ME_DS_ADMIN_SECRET
# DS → Backend URL
# IMPORTANT: Java reads DS_BACKEND_INTERNAL_URL
# Unity has "Disallow Downloads Over HTTP" ON — must use HTTPS via nginx.
DS_BACKEND_INTERNAL_URL=https://\${VPS_IP}
DS_DOCKER_BACKEND_INTERNAL_URL=https://\${VPS_IP}
# DS port pool: must NOT overlap with relay (7777-7900)
DS_PORT_START=9000
DS_PORT_END=9100
DS_MAX_PLAYERS=16
DS_MAX_MEMORY_MB=512

# GHCR — backend pulls DS image (private registry)
# PAT: https://github.com/settings/tokens → Classic → read:packages
GHCR_OWNER=nvanquyet
GHCR_TOKEN=CHANGE_ME_GITHUB_PAT_READ_PACKAGES

# ── Dashboard ─────────────────────────────────────────────────
DASHBOARD_PORT=3000
DASHBOARD_BACKEND_URL=http://nighthunt-backend:8080
DASHBOARD_ADMIN_USER=admin
DASHBOARD_ADMIN_PASS=CHANGE_ME_ADMIN_PASSWORD
DASHBOARD_ROOT_USER=root
DASHBOARD_ROOT_PASS=CHANGE_ME_ROOT_PASSWORD
EOF
  echo ""
  echo "    ┌─────────────────────────────────────────────────────┐"
  echo "    │  ⚠️  QUAN TRỌNG: Chỉnh sửa file trước khi chạy!   │"
  echo "    │  nano ${ENV_FILE}                         │"
  echo "    │                                                     │"
  echo "    │  Các giá trị BẮT BUỘC thay đổi:                   │"
  echo "    │    MYSQL_PASSWORD, MYSQL_ROOT_PASSWORD              │"
  echo "    │    REDIS_PASSWORD                                   │"
  echo "    │    JWT_SECRET  (openssl rand -hex 32)               │"
  echo "    │    ADMIN_SECRET                                      │"
  echo "    │    GHCR_TOKEN  (PAT: read:packages)                 │"
  echo "    │    API_BASE_URL / CORS_ALLOWED_ORIGINS (domain)     │"
  echo "    └─────────────────────────────────────────────────────┘"
  echo ""
else
  echo "==> .env.production đã tồn tại — bỏ qua"
fi

# ── 6. Cấu hình Firewall (ufw) ──────────────────────────────────────────────
if command -v ufw &>/dev/null; then
  echo "==> Cấu hình firewall (ufw)..."
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing
  # SSH — phải allow trước để không bị lock out
  ufw allow 22/tcp   comment 'SSH'
  # HTTP + HTTPS — nginx
  ufw allow 80/tcp   comment 'HTTP (Let'\''s Encrypt ACME)'
  ufw allow 443/tcp  comment 'HTTPS (nginx)'
  # UDP relay — cross-network custom game sessions (relay_server.py)
  ufw allow 7777:7900/udp comment 'NightHunt relay UDP game sessions'
  # UDP DS game ports — dedicated server containers
  ufw allow 9000:9100/udp comment 'NightHunt DS game ports'
  # Internal ports — KEEP CLOSED externally
  # 8080 (backend), 3306 (mysql), 6379 (redis), 3000 (dashboard), 7776 (relay mgmt)
  ufw --force enable
  echo "    [OK] Firewall configured"
  ufw status verbose
else
  echo "==> ufw không có, bỏ qua — hãy tự cấu hình firewall:"
  echo "    Allow 80/tcp, 443/tcp, 22/tcp"
  echo "    Allow 7777-7900/udp  (relay)"
  echo "    Allow 9000-9100/udp  (DS game ports)"
  echo "    Block 8080, 3306, 6379, 3000, 7776"
fi

# ── 7. Tạo SSH key cho GitHub Actions deploy ─────────────────────────────────
SSH_KEY_FILE="/root/.ssh/nighthunt_deploy"
  echo "==> Tạo SSH deploy key..."
  ssh-keygen -t ed25519 -C "github-actions-deploy" -f "$SSH_KEY_FILE" -N ""
  cat "${SSH_KEY_FILE}.pub" >> /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
  echo ""
  echo "    ┌─────────────────────────────────────────────────────┐"
  echo "    │  Copy PRIVATE KEY này vào GitHub Secret VPS_SSH_KEY │"
  echo "    └─────────────────────────────────────────────────────┘"
  echo ""
  cat "$SSH_KEY_FILE"
  echo ""
  echo "    [OK] SSH key tạo xong"
else
  echo "==> SSH deploy key đã tồn tại"
  echo "    Private key: $SSH_KEY_FILE"
fi

# ── 8. Tạo SSL cert (self-signed cho dev/testing) ───────────────────────────
CERT_DIR="${DEPLOY_DIR}/certs"
if [ ! -f "${CERT_DIR}/keystore.p12" ]; then
  echo "==> Tạo self-signed SSL cert..."
  keytool -genkeypair \
    -alias nighthunt \
    -keyalg RSA \
    -keysize 2048 \
    -validity 3650 \
    -keystore "${CERT_DIR}/keystore.p12" \
    -storetype PKCS12 \
    -storepass nighthunt-dev \
    -dname "CN=nighthunt,OU=nighthunt,O=nighthunt,L=HCM,S=HCM,C=VN" \
    2>/dev/null && echo "    [OK] SSL cert created" || echo "    [SKIP] keytool không có, tự copy cert vào ${CERT_DIR}/"
else
  echo "==> SSL cert đã tồn tại"
fi

# ── Tóm tắt ─────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   Setup hoàn tất!                           ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Việc cần làm tiếp theo:"
echo ""
echo "  1. Chỉnh sửa .env.production:"
echo "       nano ${ENV_FILE}"
echo ""
echo "  2. Thêm vào GitHub Secrets (repo nighthunt_server):"
echo "       VPS_HOST     = $(curl -s ifconfig.me 2>/dev/null || echo '<IP VPS>')"
echo "       VPS_USER     = root"
echo "       VPS_SSH_KEY  = nội dung file ${SSH_KEY_FILE}"
echo "       GHCR_TOKEN   = GitHub PAT (scope: read:packages)"
echo ""
echo "  3. (Lần đầu) Kéo image và khởi động stack:"
echo "       cd ${DEPLOY_DIR}"
echo "       echo '<GHCR_TOKEN>' | docker login ghcr.io -u nvanquyet --password-stdin"
echo "       docker compose --env-file .env.production pull"
echo "       docker compose --env-file .env.production up -d"
echo ""
